
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.colors-by-example]
audit-as-crates-io = true

[[exemptions.approx]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.0"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.0"
criteria = "safe-to-deploy"

[[exemptions.env_logger]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.fast-srgb8]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.153"
criteria = "safe-to-deploy"

[[exemptions.owo-colors]]
version = "4.0.0"
criteria = "safe-to-deploy"

[[exemptions.palette]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.palette_derive]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.0"
criteria = "safe-to-deploy"
